### PR TITLE
Index ncdf groups and subgroups

### PR DESCRIPTION
**Pull request by AntoineRenaud91**
This pull request focuses on the indexing of groups and subgroups within a NetCDF file. Below is a Rust example demonstrating the intended behavior:
```rust
let path = std::env::temp_dir().join("test_index_groups.nc");
// Create mock netcdf file
{
    let mut ncfile = netcdf::create(path.clone()).unwrap();
    ncfile.add_dimension("x", 1).unwrap();
    ncfile.add_variable::<f64>("x", &["x"]).unwrap().put_values(&[1.0], ..).unwrap();
    let mut ab = ncfile.add_group("a/b").unwrap();
    ab.add_dimension("x", 1).unwrap();
    ab.add_variable::<f64>("x", &["x"]).unwrap()put_values(&[1.0], ..).unwrap();
    let mut abc = ab.add_group("c").unwrap();
    abc.add_dimension("x", 1).unwrap();
    abc.add_variable::<f64>("x", &["x"]).unwrap().put_values(&[1.0], ..).unwrap();
}
let idx = Index::index(path).unwrap();
assert_eq!(idx.datasets.len(), 3);
assert!(idx.datasets.contains_key("x"));
assert!(idx.datasets.contains_key("a/b/x"));
assert!(idx.datasets.contains_key("a/b/c/x"));
```
Note: The dataset naming convention is designed to remain unchanged when indexing NetCDF file where only the root group is populated.

### CODE REVIEW

**Comment by gauteh** [comment]
Thank you, also check the discussion here: https://github.com/gauteh/hidefix/pull/28, https://github.com/gauteh/hidefix/issues/25 and here https://github.com/gauteh/hidefix/issues/24.

**Comment by AntoineRenaud91** [comment]
Ok, I have should have checked the issue.

**Comment by gauteh** [comment]
> Ok, I have should have checked the issue.

No problem, the work stopped for a bit. But I wonder if introducing Group types and using DeRef is the best solution.

**Comment by AntoineRenaud91** [comment]
I just pushed the refactoring with the new GroupIndex type making Index deref into GroupIndex. I kept the path format api "a/b/c/x" to access a dataset within a subgroup.

But the serialize test is failing, could you help me there ?

**Comment by gauteh** [comment]
Nice, this looks promising! Just what I had in mind. I'll take a look in a bit, no time right this moment.

**Comment by gauteh** [comment]
> This pull request focuses on the indexing of groups and subgroups within a NetCDF file. Below is a Rust example demonstrating the intended behavior:

Maybe this can be cleaned up and included in the documentation?

**Comment by gauteh** [comment]
> But the serialize test is failing, could you help me there ?

Fixed this. Let me know when it is ready to be merged.

**Comment by AntoineRenaud91** [comment]
Thanks for the fix. I'll clean it up and update some docs.

Can I ask you another question here (I am not sure if there is a way to chat somewhere on github) ?
I am having trouble understanding how to use Reader or Streamer to have an efficient paralell query to the data. 

I would like to have an object from which I can query values  for given indices while multiple queries can be done in parallel.

Say I want to this:
```rust
use hidefix::prelude::*;
fn main() {
    let path = std::env::temp_dir().join("test.nc");
    let data = [0.,1.,2.,3.];
    {
        let mut file = netcdf::create(path.clone()).unwrap();
        file.add_dimension("x", 2).unwrap();
        file.add_dimension("y", 2).unwrap();
        let mut var = file.add_variable::<f64>("data", &["x", "y"]).unwrap();
        var.put_values(&data.clone(), ..).unwrap();
    }
    let idx = Index::index(path).unwrap();
    let mut reader = idx.reader("data").unwrap();
    for _ in 0..1000 {
        assert_eq!(reader.values::<f64>(Some(&[1,0]),Some(&[1,1])).unwrap()[0],data[2]);
    }
}
```

But reader needs to be mutable, so I am not sure how I could go easily parallel here.

**Comment by AntoineRenaud91** [comment]
I could do something like this:
```rust
use std::sync::Arc;

use hidefix::prelude::*;
fn main() {
    let path = std::env::temp_dir().join("test.nc");
    let data = Arc::new([0.,1.,2.,3.]);
    {
        let mut file = netcdf::create(path.clone()).unwrap();
        file.add_dimension("x", 2).unwrap();
        file.add_dimension("y", 2).unwrap();
        let mut var = file.add_variable::<f64>("data", &["x", "y"]).unwrap();
        var.put_values(&data[..], ..).unwrap();
    }
    let idx = Arc::new(Index::index(path).unwrap());
    let handles = (0..10).map(|_| {
        let idx = idx.clone();
        let data = data.clone();
        std::thread::spawn( move || {
            assert_eq!(idx.reader("data").unwrap().values::<f64>(Some(&[1,0]),Some(&[1,1])).unwrap()[0],data[2]);
        })
    }).collect::<Vec<_>>();
    handles.into_iter().for_each(|h| h.join().unwrap())
}
```

But I feel that I am missing something.

**Comment by gauteh** [comment]
This test creates multiple readers from the index, then use those in parallel. That seems like the closest to your use case: https://github.com/gauteh/hidefix/blob/main/benches/concurrency.rs#L79

**Comment by gauteh** [comment]
I added some examples here:
* https://github.com/gauteh/hidefix/blob/main/examples/read_hfx_concurrent.rs
* https://github.com/gauteh/hidefix/blob/main/examples/read_hfx_parallel.rs

**Comment by AntoineRenaud91** [comment]
Thanks, I have pushed some docs. Let me know, if you need more.

Thanks for your help. Still I think there is something I don't understand. Because it is really slow. Perhaps it has to do with the fact that I want to parallelize multiple single point requests.

**Comment by gauteh** [comment]
Do you have an example dataset or example use-case that we could add to the benchmarks? Possibly also using the existing data.

**Comment by gauteh** [comment]
I will try to update this PR to the new main and do a new release. We have two big new things, groups + extent!

**Comment by gauteh** [comment]
Finally got the time to rebase this. Thanks!

**Pull request merged**
