### PR TITLE
Use hdf5-metno fork

### PR DESCRIPTION
**Pull request by magnusuMET**

### CODE REVIEW

**Comment by gauteh** [comment]
Looks like there's an issue with thread-safety in hdf5? Could also explain the weird issues in the other tests.

**Comment by magnusuMET** [comment]
It does not look like we require a threadsafe `hdf5` since we use `hdf5` for all operations (which serialises all calls to hdf5)

**Comment by magnusuMET** [comment]
That broke a lot of tests... I will test if it works if `netcdf` uses the same lock as `hdf5` as tests pass when not using default features

**Comment by gauteh** [comment]
> That broke a lot of tests... I will test if it works if `netcdf` uses the same lock as `hdf5` as tests pass when not using default features

I think it breaks since rust runs the tests in parallel, they could be run in series on windows to avoid the problem.

**Comment by magnusuMET** [comment]
@gauteh Calls to `hdf5` should be serialised properly now, even from `netcdf`

**Comment by gauteh** [comment]
Thanks!

**Pull request merged**
