### PR TITLE
WIP: Enable reading groups from HDF5

### PR DESCRIPTION
**Pull request by weiji14**
Allow hidefix to read groups in a HDF5 file.

Currently just adding a placeholder unit test that lists the group member names, and added a sample HDF5 file (will delete it or find a smaller one later). I'll refactor this PR once I get my head around Rust a bit more, but feel free to leave comments/suggestions.

Towards fixing #24.

References:
- https://docs.rs/hdf5/latest/hdf5/struct.Group.html#method.group

### CODE REVIEW

**Comment by gauteh** [comment]
Sounds good, I also sometimes download the file during the test: https://github.com/gauteh/hidefix/blob/main/tests/read_norkyst.rs#L12, but those files are much bigger than this one. You could also even generate it using the native hdf5 bindings.

**Comment by weiji14** [comment]
Sorry, was away with a few conferences/trips the past month, so haven't managed to find time to work on this. I see that there's another PR at #31 now, so happy for that to go ahead and close this one if needed.

**Comment by gauteh** [comment]
Yeah, I think that one is probably further ahead: but it became outdated after some other changes, so it requires some work before it can be merged (otherwise it is ready).

**Comment by gauteh** [comment]
Closed in favor of #31.

**Pull request closed without merging**
