### PR TITLE
update to hdf5 0.8, not using custom hdf5 library

### PR DESCRIPTION
**Pull request by gauteh**

### CODE REVIEW

**Comment by magnusuMET** [comment]
This branch should be rebased on master to get CI

**Comment by gauteh** [comment]
We also need to add CI with --fast-index feature enabled.

**Comment by gauteh** [comment]
This is now using fast-index by default, so that's what is tested at the moment.

**Comment by gauteh** [comment]
Oh, that's useful. Should've asked you to review first :D

**Pull request merged**
